version: '3.8'

services:
  nextapp:
    container_name: nextapp
    build:
      dockerfile: Dockerfile.frontend
    ports:
      - "80:80"
    environment:
      - NEXT_PUBLIC_API_URL=http://flaskapp:5000
    depends_on:
      - flaskapp

  flaskapp:
    container_name: flaskapp
    build:
      dockerfile: Dockerfile.backend
    ports:
      - '5000:5000'
    restart: always
