  version: '3.8'

  services:
    nginx:
      container_name: nginx
      image: healthmonitor.azurecr.io/hba1c-monitor-nginx:latest
      ports:
        - "80:80"  # Expose port 80 for external access
      volumes:
        - ./nginx.conf:/etc/nginx/nginx.conf:ro  # Mount custom Nginx configuration
      depends_on:
        - nextapp
        - flaskapp

    nextapp:
      container_name: nextapp
      image: healthmonitor.azurecr.io/hba1c-monitor-nextapp:latest
      expose:
        - "80"  # Expose port 80 for Nginx to connect
      environment:
        - NEXT_PUBLIC_API_URL=https://healthmonitor-c4ceejh2fdhfh6hj.swedencentral-01.azurewebsites.net  # Use base API URL (without /api)
      depends_on:
        - flaskapp

    flaskapp:
      container_name: flaskapp
      image: healthmonitor.azurecr.io/hba1c-monitor-flaskapp:latest
      expose:
        - "80"  # Expose port 80 for Nginx to connect
      volumes:
        - ./readings.json:/app/readings.json
        - ./conversations.json:/app/conversations.json
      restart: always
